apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sysdig-image-scanner.name" . }}-token
  namespace: {{ .Release.namespace }}
  labels:
    {{ include "sysdig-image-scanner.labels" . | nindent 4 }}
stringData:
  {{- if eq (default "" .Values.sysdigSecureToken) "" }}{{ fail "value 'sysdigSecureToken' is mandatory, but it is not set"}}{{ end }}
  SYSDIG_SECURE_TOKEN: {{ .Values.sysdigSecureToken }}